name = "Pigeons"
uuid = "0eb8d820-af6a-4919-95ae-11206f830c31"
authors = ["Alexandre Bouchard-Côté <bouchard@stat.ubc.ca>, Nikola Surjanovic <nikola.surjanovic@stat.ubc.ca>, Paul Tiede <ptiede91@gmail.com>, Trevor Campbell <trevor@stat.ubc.ca>, Miguel Biron-Lattes <miguel.biron@stat.ubc.ca>, Saifuddin Syed <saifuddin.syed@stats.ox.ac.uk>"]
version = "0.4.10"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Expect = "6a31a4e8-6e70-5a2d-b005-bc2d500d80a5"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OnlineStatsBase = "925886fa-5bf2-5e8e-b522-a9147a512338"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SplittableRandoms = "8efc31e9-3fb0-4277-b18c-5a3d5d07abad"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[weakdeps]
AbstractPPL = "7a57a42e-76ec-4ea3-a279-07e840d6d9cf"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JuliaBUGS = "ba9fb4c0-828e-4473-b6a1-cd2560fee5bf"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"

[extensions]
PigeonsBridgeStanExt = "BridgeStan"
PigeonsDynamicPPLExt = ["DynamicPPL", "DifferentiationInterface"]
PigeonsEnzymeExt = "Enzyme"
PigeonsForwardDiffExt = "ForwardDiff"
PigeonsHypothesisTestsExt = "HypothesisTests"
PigeonsJuliaBUGSExt = ["JuliaBUGS", "AbstractPPL", "Bijectors"]
PigeonsMCMCChainsExt = "MCMCChains"
PigeonsReverseDiffExt = "ReverseDiff"

[compat]
ADTypes = "1.14.0"
AbstractPPL = "0.8.4, 0.9, 0.10, 0.11"
Bijectors = "0.13, 0.14, 0.15"
BridgeStan = "2"
DataFrames = "1"
DataStructures = "0.9.0"
DifferentiationInterface = "0.6.48"
Distributions = "0.25"
DocStringExtensions = "0.9"
DynamicPPL = "0.35, 0.38"
Enzyme = "0.12, 0.13"
Expect = "0.3"
FillArrays = "1"
ForwardDiff = "0.10"
Graphs = "1"
HypothesisTests = "0.11"
Interpolations = "0.14, 0.15"
JSON = "0.21"
JuliaBUGS = "0.8, 0.9"
LogDensityProblems = "2"
LogDensityProblemsAD = "1"
LogExpFunctions = "0.3"
MCMCChains = "6, 7"
MPI = "0.20"
MPIPreferences = "0.1"
MacroTools = "0.5"
OnlineStatsBase = "1"
OrderedCollections = "1"
RecipesBase = "1"
Requires = "1"
ReverseDiff = "1"
Roots = "2"
SpecialFunctions = "2"
SplittableRandoms = "0.1"
StaticArraysCore = "1"
Statistics = "1"
StatsBase = "0.33, 0.34"
ZipFile = "0.10"
julia = "1.8"

[extras]
AbstractPPL = "7a57a42e-76ec-4ea3-a279-07e840d6d9cf"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JuliaBUGS = "ba9fb4c0-828e-4473-b6a1-cd2560fee5bf"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
