name: Update stored benchmarking result
on:
  push:
    paths:
      - 'Project.toml'
      - 'src/**'
      - 'ext/**'
      - 'bench/**'
    branches:
      - main  

jobs:
  update-benchmarks:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2

      - name: Run benchmarking
        run: |
          julia bench/benchmark.jl bench/benchmark.csv
          julia -e "using InteractiveUtils; versioninfo()" > bench/benchmark_metainfo.log
          sed -i '/Environment:/,$d' bench/benchmark_metainfo.log


      - name: Commit new benchmark results
        uses: stefanzweifel/git-auto-commit-action@v5

